documentation:
- changed-files:
  - any-glob-to-any-file: [
    '**/*.md',
    '**/*.mdx'
  ]

test:
- changed-files:
  - any-glob-to-any-file: [
    '**/*.test.ts',
    '**/*.test.tsx',
    '**/*.spec.ts',
    '**/*.spec.tsx'
  ]

prettier rules 💅:
- changed-files:
  - any-glob-to-any-file: ['index.js']

github actions:
- changed-files:
  - any-glob-to-any-file: ['.github/**/*']
